import { DEFAULT_PARAMS, defaultPlanName } from './constants.js';

export function createInitialPlanState({ initialPlanId, planToolbar, runSummaryRefs }) {
  return {
    loading: false,
    generating: false,
    activePlanningPeriodId: null,
    versions: [],
    selectedVersionId: null,
    ruleProfiles: [],
    selectedRuleProfileId: null,
    rulesDefinition: null,
    ruleBaseBools: new Map(),
    ruleBaseWeights: new Map(),
    ruleValuesBools: new Map(),
    ruleValuesWeights: new Map(),
    ruleDefinitionByKey: new Map(),
    ruleExtraContainers: new Map(),
    ruleBackendDefaultsBools: new Map(),
    ruleBackendDefaultsWeights: new Map(),
    planName: defaultPlanName(),
    planComment: '',
    generatedPlans: [],
    lastPlanId: null,
    subjects: new Map(),
    classes: new Map(),
    teachers: new Map(),
    rooms: new Map(),
    boolInputs: new Map(),
    weightInputs: new Map(),
    params: { ...DEFAULT_PARAMS },
    paramInputs: new Map(),
    analysis: null,
    analysisError: null,
    activeTab: 'results',
    debugRuns: [],
    debugRunning: false,
    debugStale: true,
    visibleClasses: new Set(),
    initialPlanId,
    ruleGroupSections: new Map(),
    ruleGroupCollapsed: new Map(),
    editing: null,
    editingParkingSeq: 0,
    dragPayload: null,
    highlightedTeacherId: null,
    runSummary: runSummaryRefs,
    planToolbar,
    classWindows: new Map(),
  };
}
