from __future__ import annotations


def get_rule_definitions() -> dict:
    return {
        "bools": [
            {
                "key": "stundenbedarf_vollstaendig",
                "label": "Alle Requirements vollständig planen",
                "default": True,
                "info": "Jede geforderte Unterrichtsstunde wird eingeplant (keine Unterdeckung).",
            },
            {
                "key": "keine_lehrerkonflikte",
                "label": "Lehrkraft nicht doppelt belegen",
                "default": True,
                "info": "Verhindert, dass eine Lehrkraft gleichzeitig zwei Klassen unterrichtet.",
            },
            {
                "key": "keine_klassenkonflikte",
                "label": "Klasse nicht doppelt belegen",
                "default": True,
                "info": "Sichert, dass jede Klasse pro Slot höchstens ein Fach hat.",
            },
            {
                "key": "raum_verfuegbarkeit",
                "label": "Raumverfügbarkeiten aus Basisplan berücksichtigen",
                "default": True,
                "info": "Sperrt Räume in Slots, die im Basisplan als nicht verfügbar markiert sind.",
            },
            {
                "key": "basisplan_fixed",
                "label": "Feste Slots aus Basisplan erzwingen",
                "default": True,
                "info": "Übernimmt alle fix eingetragenen Basisplan-Stunden ohne Änderungen.",
            },
            {
                "key": "basisplan_flexible",
                "label": "Flexible Slot-Gruppen aus Basisplan respektieren",
                "default": True,
                "info": "Wählt genau einen Slot aus jeder Basisplan-Optionengruppe.",
            },
            {
                "key": "basisplan_windows",
                "label": "Basisplan-Zeitfenster (Klassen) respektieren",
                "default": True,
                "info": "Sperrt Unterrichtszeiten einer Klasse gemäß den Basisplan-Fenstern.",
            },
            {
                "key": "stundenbegrenzung",
                "label": "Tageslimit (Mo–Do 6, Fr 5)",
                "default": True,
                "info": "Limitiert Unterricht auf 6 Stunden (Mo–Do) bzw. 5 Stunden (Fr).",
            },
            {
                "key": "stundenbegrenzung_erste_stunde",
                "label": "Bei vollem Tag 1. Stunde belegen",
                "default": True,
                "info": "Wenn der Tag voll ist, wird die erste Stunde automatisch belegt.",
            },
            {
                "key": "fach_nachmittag_regeln",
                "label": "Fachspezifische Nachmittag-Regeln anwenden",
                "default": True,
                "info": "Beachtet pro Requirement die Vorgabe 'Nachmittag muss/kann/nein'.",
            },
            {
                "key": "nachmittag_pause_stunde",
                "label": "Nachmittag mit freier 6. Stunde",
                "default": False,
                "info": "Ist Unterricht am Nachmittag geplant, bleibt die 6. Stunde frei.",
            },
            {
                "key": "lehrer_hohlstunden_soft",
                "label": "Lehrer-Hohlstunden (Soft)",
                "default": True,
                "info": "Versucht Hohlstunden für Lehrkräfte zu vermeiden und straft Überschreitungen weich ab.",
            },
            {
                "key": "lehrer_arbeitstage",
                "label": "Lehrer nur an Arbeitstagen einplanen",
                "default": True,
                "info": "Respektiert die in der Lehrerpflege hinterlegten Arbeitstage.",
            },
            {
                "key": "keine_hohlstunden",
                "label": "Hohlstunden minimieren (Soft)",
                "default": True,
                "info": "Bestraft einzelne Hohlstunden innerhalb eines Tages.",
            },
            {
                "key": "keine_hohlstunden_hard",
                "label": "Keine Hohlstunden (Hard)",
                "default": False,
                "info": "Verbietet Hohlstunden vollständig (streng).",
            },
            {
                "key": "doppelstundenregel",
                "label": "Doppelstunden-Regel (max 2 in Folge)",
                "default": True,
                "info": "Setzt Doppelstunden gemäß Muss/Kann/Nein und verhindert Dreierblöcke.",
            },
            {
                "key": "einzelstunde_nur_rand",
                "label": "Einzelstunde nur Rand (bei DS=muss)",
                "default": True,
                "info": "Bei Pflicht-Doppelstunden dürfen Einzelstunden nur an Randpositionen liegen.",
            },
            {
                "key": "bandstunden_parallel",
                "label": "Bandfächer parallel planen",
                "default": True,
                "info": "Lege Bandfächer (is_bandfach) parallel in allen beteiligten Klassen und verteilt sie auf unterschiedliche Tage.",
            },
            {
                "key": "band_lehrer_parallel",
                "label": "Bandfächer dürfen denselben Lehrer haben",
                "default": True,
                "info": "Erlaubt einer Lehrkraft, mehrere Klassen desselben Bandfachs gleichzeitig zu unterrichten.",
            },
            {
                "key": "gleichverteilung",
                "label": "Gleichverteilung über Woche (Soft)",
                "default": True,
                "info": "Sorgt soft dafür, dass Tageslasten möglichst gleich verteilt sind.",
            },
            {
                "key": "mittagsschule_vormittag",
                "label": "Vormittagsminimum je Tag",
                "default": True,
                "info": "Verlangt an jedem Tag mindestens vier Stunden Unterricht vor der Mittagspause.",
            },
        ],
        "weights": [
            {
                "key": "W_GAPS_START",
                "label": "Gewicht Startlücke",
                "default": 2,
                "min": 0,
                "max": 50,
                "info": "Penalty für freie erste Stunde, wenn danach Unterricht folgt.",
            },
            {
                "key": "W_GAPS_INSIDE",
                "label": "Gewicht Hohlstunden (innen)",
                "default": 3,
                "min": 0,
                "max": 50,
                "info": "Penalty für Lücken zwischen zwei belegten Stunden.",
            },
            {
                "key": "W_EVEN_DIST",
                "label": "Gewicht Gleichverteilung",
                "default": 1,
                "min": 0,
                "max": 50,
                "info": "Penalty für Tagesabweichungen von der durchschnittlichen Klassenlast.",
            },
            {
                "key": "W_EINZEL_KANN",
                "label": "Gewicht Einzelstunden-Penalty (DS=kann)",
                "default": 5,
                "min": 0,
                "max": 50,
                "info": "Penalty für Einzelstunden, wenn Doppelstunden optional erlaubt sind.",
            },
            {
                "key": "W_EINZEL_SOLL",
                "label": "Gewicht Doppelstunde bevorzugt (DS=soll)",
                "default": 8,
                "min": 0,
                "max": 50,
                "info": "Strafgewicht für fehlende Doppelstunden, wenn sie bevorzugt geplant werden sollen.",
            },
            {
                "key": "W_BAND_OPTIONAL",
                "label": "Gewicht optionale Bandteilnahme",
                "default": 6,
                "min": 0,
                "max": 50,
                "info": "Strafgewicht, wenn optionale Bandteilnehmer nicht mit dem Band eingeplant werden.",
            },
            {
                "key": "TEACHER_GAPS_DAY_MAX",
                "label": "Lehrer-Lücken pro Tag",
                "default": 1,
                "min": 0,
                "max": 6,
                "info": "Zulässige Anzahl an Hohlstunden pro Lehrkraft und Tag, bevor Strafpunkte greifen.",
            },
            {
                "key": "TEACHER_GAPS_WEEK_MAX",
                "label": "Lehrer-Lücken pro Woche",
                "default": 3,
                "min": 0,
                "max": 20,
                "info": "Zulässige Hohlstunden pro Lehrkraft und Woche.",
            },
            {
                "key": "W_TEACHER_GAPS",
                "label": "Gewicht Lehrer-Hohlstunden",
                "default": 2,
                "min": 0,
                "max": 50,
                "info": "Strafgewicht für Lehrkräfte-Hohlstunden über den erlaubten Grenzen.",
            },
        ],
    }
